apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: tkc-ray
spec:
  distribution:
    version: v1.21
  topology:
    controlPlane:
      class: best-effort-large
      count: 1
      storageClass: tkc
    workers:
      class: best-effort-medium
      count: 2
      storageClass: tkc
  settings:
    storage:
      classes: ["tkc"]              #Named PVC storage classes
      defaultClass: tkc                     #Default PVC storage class
